import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import Providers from "./providers";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    images: [
      {
        url: "/next.svg",
        width: 512,
        height: 512,
      },
    ],
    type: "website",
    siteName: "Create Next App",
    locale: "en_US",
    ttl: 60,
    videos: [],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/next.svg"],
    creator: "@vercel",
    title: "Create Next App",
    description: "Generated by create next app",
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
