import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    openGraph: {
        title: "Create Next App",
        description: "Generated by create next app",
        images: [
            {
                url: "/next.svg",
                width: 512,
                height: 512,
            },
        ],
        type: "website",
        siteName: "Create Next App",
        locale: "en_US",
        ttl: 60,
        videos: [],
    },
    twitter: {
        card: "summary_large_image",
        images: ["/next.svg"],
        creator: "@vercel",
        title: "Create Next App",
        description: "Generated by create next app",
    },
};

interface HomePageProps {
    children: React.ReactNode;
}


export default function HomePage({ children }: HomePageProps) {
    return (
        <div className="container max-w-[100rem] mx-auto px-[.6rem] py-4 flex flex-col items-center gap-4">
            {children}
        </div>
    );
}